name: API Tests (Docker + Pytest + Allure)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t restful-tests .

      - name: Run tests in container
        run: docker run --rm -v $(pwd)/reports:/app/reports restful-tests

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/

      - name: Generate Allure Report
        run: |
            pip install allure-pytest
            wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
            tar -zxvf allure-2.29.0.tgz
            ./allure-2.29.0/bin/allure generate reports --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report